### ISSUE TITLE
你好RN0.61.4报错是什么原因呢？

### ISSUE THREAD

**Issue by SemperChen** [xiaoxinbo118/react-native-sns-share#1]
* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find :alipaySdk-15.6.5-20190718211159-noUtdid:.
     Required by:
         project :app > project :react-native-sns-share
   > Could not find com.sina.weibo.sdk:core:4.4.1.
     Searched in the following locations:
       - file:/Users/beatyourself/.m2/repository/com/sina/weibo/sdk/core/4.4.1/core-4.4.1.pom
       - file:/Users/beatyourself/.m2/repository/com/sina/weibo/sdk/core/4.4.1/core-4.4.1-openDefaultRelease.aar
       - file:/Users/beatyourself/Documents/projects/gitee/Newsletter/node_modules/react-native/android/com/sina/weibo/sdk/core/4.4.1/core-4.4.1.pom
       - file:/Users/beatyourself/Documents/projects/gitee/Newsletter/node_modules/react-native/android/com/sina/weibo/sdk/core/4.4.1/core-4.4.1-openDefaultRelease.aar
       - file:/Users/beatyourself/Documents/projects/gitee/Newsletter/node_modules/jsc-android/dist/com/sina/weibo/sdk/core/4.4.1/core-4.4.1.pom
       - file:/Users/beatyourself/Documents/projects/gitee/Newsletter/node_modules/jsc-android/dist/com/sina/weibo/sdk/core/4.4.1/core-4.4.1-openDefaultRelease.aar
       - https://dl.google.com/dl/android/maven2/com/sina/weibo/sdk/core/4.4.1/core-4.4.1.pom
       - https://dl.google.com/dl/android/maven2/com/sina/weibo/sdk/core/4.4.1/core-4.4.1-openDefaultRelease.aar
       - https://jcenter.bintray.com/com/sina/weibo/sdk/core/4.4.1/core-4.4.1.pom
       - https://jcenter.bintray.com/com/sina/weibo/sdk/core/4.4.1/core-4.4.1-openDefaultRelease.aar
       - https://jitpack.io/com/sina/weibo/sdk/core/4.4.1/core-4.4.1.pom
       - https://jitpack.io/com/sina/weibo/sdk/core/4.4.1/core-4.4.1-openDefaultRelease.aar
     Required by:
         project :app > project :react-native-sns-share
   > Could not find :open_sdk_r6137_lite:.
     Required by:
         project :app > project :react-native-sns-share

**Comment by xiaoxinbo118** [comment]
看日志的情况是 QQ的AndroidSDK没下载到。 我尝试了下，是可以更新到的。
