### ISSUE TITLE
1.3.4 Android无法运行

### ISSUE THREAD

**Issue by alleniver** [xiaoxinbo118/react-native-sns-share#10]
我看了下源文件,WXEntryActivity.java这个文件好像少了一个包
import android.content.Intent;
这个文件少了一个包,作者可以补一下吗?

**Comment by alleniver** [comment]
我用patch-package打了个补丁也一样.

**Comment by xiaoxinbo118** [comment]
感谢使用。 升级到1.3.5版本了。 修复了这个少引用包的问题
