### ISSUE TITLE
这个组件出发点挺好的,只集成主流的功能,不过RN 0.62也运行不起来.

### ISSUE THREAD

**Issue by alleniver** [xiaoxinbo118/react-native-sns-share#4]
系统环境:
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 666.20 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.0 => 0.62.0 

今天试了最新的RN 0.62 发现用了
Sns.snsSocial.registerApp这个方法后,应用就直接奔溃.
希望能解决下这个问题,这个组件挺好的.

**Comment by xiaoxinbo118** [comment]
初步判断下来是因为demo里我放的微博的key是假的。 weibo的sdk抛了异常。 你可以放一个真的key试验一下。 后面我会加上这部分的异常处理。
感谢使用。

**Comment by xiaoxinbo118** [comment]
感谢使用。
初步判断是 微博的初始化出了问题。 因为时间问题，暂时我还没办法修复。不过可以在注册的时候降级。

Sns.snsSocial.registerApp({
  'wechart': 'wx111111',
  'weibo': null,
  'qq': '3333333',
}, {
  'weibo': null,
}, 'testing');

先屏蔽weibo功能。后续版本中我去修复weibo的问题。 

如果有时间话，也请帮忙试验下，用真机+正确的weiboId试验一下。 
再次感谢使用。

**Comment by xiaoxinbo118** [comment]
另外项目中依赖的微博SDK版本是4.4.1

https://github.com/sinaweibosdk/weibo_android_sdk

**Comment by alleniver** [comment]
嗯,我这几天会用到,我会仔细再测试一下,感觉这个组件对国内用户还是挺有用的,功能实用简洁.做的不错!
