### ISSUE TITLE
安卓支付宝支付闪退

### ISSUE THREAD

**Issue by Forest337** [xiaoxinbo118/react-native-sns-share#6]
安卓支付宝支付闪退    

I/Timeline: Timeline: Activity_launch_request time:243042332
I/ReactNativeJS: app杀死
W/BpBinder: Slow Binder: BpBinder transact took 4423ms, interface=com.alipay.android.app.IAlixPay, code=1 oneway=false
I/System.out: resultStatus={null};memo={null};result={null}
    null
W/Thread-6: type=1400 audit(0.0:341705): avc: denied { read } for name="version" dev="proc" ino=4026532078 scontext=u:r:untrusted_app_27:s0:c46,c257,c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=0
I/ReactNativeJS: { [Error: pay failed]
      framesToPop: 1,
      nativeStackAndroid: [],
      userInfo: null,
      code: '0',
      line: 14,
      column: 1741,
      sourceURL: 'index.android.bundle' }
I/ReactNativeJS: 进入
W/unknown:ReconnectingWebSocket: Couldn't connect to "ws://localhost:8081/message?device=MI%20CC%209%20-%2010%20-%20API%2029&app=com.beershop&clientid=DevSupportManagerImpl", will silently retry
W/com.beershop: Accessing hidden method Landroid/os/SystemProperties;-><init>()V (greylist, reflection, allowed)
W/Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
D/AudioManager: getStreamVolume isRestricted mode = 0
I/chatty: uid=10302(com.beershop) Thread-8 identical 3 lines
D/AudioManager: getStreamVolume isRestricted mode = 0

**Comment by xiaoxinbo118** [comment]
感谢使用。 
原因是支付宝的错误码返回了null，导致错误码转换时出了问题。
已在1.3.0版本中修复此问题。 请跟新版本号。"react-native-sns-share": "1.3.0"
